version: '3.9'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Santy10-tc1913
      POSTGRES_DB: techstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway:
    restart: always
    build: .
    container_name: gateway
    ports:
      - "3004:3004"
    depends_on:
      - users-service
      - products-service
      - order-service
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: techstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  users-service:
    restart: always
    build:
      context: .
      dockerfile: services/users-service/Dockerfile
    container_name: users-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: techstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  products-service:
    restart: always
    build:
      context: .
      dockerfile: services/products-service/Dockerfile
    container_name: products-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: techstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  order-service:
    restart: always
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: techstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

volumes:
  postgres_data:
