version: '3.9'
services:
  gateway:
    restart: always
    build: .
    container_name: gateway
    ports:
      - "3004:3004"
    depends_on:
      - users-service
      - products-service
      - order-service
    environment:
      DB_HOST: awstechstore.cliuqok4wqq9.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: awstechstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  users-service:
    restart: always
    build:
      context: .
      dockerfile: services/users-service/Dockerfile
    container_name: users-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: awstechstore.cliuqok4wqq9.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: awstechstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  products-service:
    restart: always
    build:
      context: .
      dockerfile: services/products-service/Dockerfile
    container_name: products-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: awstechstore.cliuqok4wqq9.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: awstechstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913

  order-service:
    restart: always
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: awstechstore.cliuqok4wqq9.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: awstechstore
      DB_USER: postgres
      DB_PASS: Santy10-tc1913
